---

- name: Install Neutron ML2 packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - openstack-neutron
    - openstack-neutron-ml2
    - openvswitch
    - openstack-neutron-openvswitch
