---

- name: Wait neutron service
  wait_for:
    host: '{{ openstack_neutron_controller_neutron_ip  }}'
    port: '{{ openstack_neutron_controller_neutron_port }}'
    delay: 3

- name: SANITY CHECK List networks
  shell: >-
    openstack
    --os-identity-api-version 3
    --os-auth-url {{ openstack_neutron_controller_keystone_protocol }}://{{ openstack_neutron_controller_keystone_hostname }}:{{ openstack_neutron_controller_keystone_port }}/v3
    --os-project-name '{{ openstack_neutron_controller_demo_project }}'
    --os-username '{{ openstack_neutron_controller_demo_user }}'
    --os-auth-type password
    --os-password '{{ openstack_neutron_controller_demo_pass }}'
    --os-user-domain-id default
    --os-project-domain-id default
    network list
  register: network_list_test
  changed_when: network_list_test.rc != 0

- debug: var=network_list_test.stdout_lines
