---

- name: Restart neutron server
  service:
    name: 'neutron-server'
    state: restarted

- name: Restart openvswitch agent
  service:
    name: 'neutron-openvswitch-agent'
    state: restarted

- name: Restart neutron L3 agent
  service:
    name: 'neutron-l3-agent'
    state: restarted

- name: Restart DHCP agent
  service:
    name: 'neutron-dhcp-agent'
    state: restarted

- name: Restart metadata agent
  service:
    name: 'neutron-metadata-agent'
    state: restarted
